version: '3'
services:
  nuxt_web:
    build: .
    image: nuxt-web:latest
    container_name: nuxt_web_sample
    tty: true
    volumes:
      - .:/app
    ports:
      - "3333:3000"
    command: >
      sh -c 'npm install && npm run dev'

